name: 森空岛每日签到

on:
  # 定时运行
  schedule:
    - cron: '0 23 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Config File
        # 将Secrets注入环境变量
        env:
          USER1_TOKEN: ${{ secrets.SKLAND_TOKEN }}
          USER2_TOKEN: ${{ secrets.SKLAND_TOKEN_2 }}
        run: |
          cat <<EOF > config.yaml
          log_level: "info"
          qmsg_key: "$QMSG_KEY"
          users:
            - nickname: "User1"
              token: "$USER1_TOKEN"
            - nickname: "User2"
              token: "$USER2_TOKEN"
          EOF
          
          echo "配置文件已生成"

      - name: Run Sign-in Script
        run: python main.py
